### ISSUE TITLE
Hardcoded path in initial-windows-deployRestInstanceStarter/tasks/main.yml

### ISSUE THREAD

**Issue by joyride9999** [siemens/fluffi#167]
The following task fails because it has "administrator" harcoded in user path. While in this case i'm logged with user "user" and there is no user "administrator".
I think it should be possible to use "%appdata%\\Microsoft\\....." or the "ansible_user" variable defined for the host.

```
- name: Fetch Rest-Instance-Starter-Autostart from "{{ftpserverURL}}/restStarter/restInstanceAutostart.bat"
  win_get_url: 
    url: "{{ftpserverURL}}/restStarter/restInstanceAutostart.bat"
    dest: "C:\\Users\\Administrator\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\restInstanceAutostart.bat"
```
